# Generated by Django 6.0.2 on 2026-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='img/')),
                ('audio', models.FileField(null=True, upload_to='aud/')),
                ('video', models.FileField(null=True, upload_to='vid/')),
            ],
        ),
    ]
