# Generated by Django 6.0.2 on 2026-02-16 07:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='img',
        ),
        migrations.AddField(
            model_name='stu',
            name='image',
            field=models.ImageField(null=True, storage=[cloudinary_storage.storage.MediaCloudinaryStorage], upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='stu',
            name='audio',
            field=models.FileField(null=True, storage=[cloudinary_storage.storage.VideoMediaCloudinaryStorage], upload_to='aud/'),
        ),
        migrations.AlterField(
            model_name='stu',
            name='video',
            field=models.FileField(null=True, storage=[cloudinary_storage.storage.VideoMediaCloudinaryStorage], upload_to='vid/'),
        ),
    ]
