# Generated by Django 6.0.2 on 2026-02-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('a', models.IntegerField()),
                ('g', models.CharField(max_length=20)),
                ('m', models.CharField(max_length=15)),
                ('e', models.EmailField(max_length=50)),
                ('d', models.CharField(max_length=50)),
                ('da', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
