# Generated by Django 6.0.3 on 2026-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=23)),
                ('contact', models.CharField(max_length=23)),
            ],
        ),
    ]
